### ISSUE TITLE
UpdateWithOptimistic 没看懂这个方法什么时候会 err 会 return nil

### ISSUE THREAD

**Issue by sjsdfg** [crossoverJie/gorm-optimistic#1]
从这个方法的实现来看。
会必返回一个 err

**Comment by crossoverJie** [comment]
@sjsdfg 可以跑一下这个单测：
https://github.com/crossoverJie/gorm-optimistic/blob/51cbac8c778b75da1ce863148da0126e55ac81bb/optimistic_lock_test.go#L15-L36

https://github.com/crossoverJie/gorm-optimistic/blob/51cbac8c778b75da1ce863148da0126e55ac81bb/optimistic_lock.go#L50
正常运行时 column.Error 为 nil.

**Comment by sjsdfg** [comment]
从代码模式来看，你是使用递归来进行重试的。

![image](https://user-images.githubusercontent.com/8037152/111725635-61186400-88a2-11eb-8e43-050b43df0d64.png)

**Comment by sjsdfg** [comment]
所以这种实现感觉有点奇怪

**Comment by sjsdfg** [comment]
```
if affected == 0
```

这里就应该加上 err 的判断
```
if affected == 0 || column.Error != nil
```
这样进入重试判断的依据

**Comment by sjsdfg** [comment]
这样来看的话，err 这里返回的也有问题。这里面只考虑了并发的异常。
但是如果是 db 异常导致的更新失败，err 信息也应该包裹进去给上层返回

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/111725923-e7cd4100-88a2-11eb-99ea-9e3f0e72e39d.png)
这里需要额外包裹 err

**Comment by crossoverJie** [comment]
@sjsdfg fixed https://github.com/crossoverJie/gorm-optimistic/commit/3d979003c59cbab339cd9afd4a937379fb07bec9
