### ISSUE TITLE
空指针异常风险

### ISSUE THREAD

**Issue by sjsdfg** [crossoverJie/gorm-optimistic#2]
![image](https://user-images.githubusercontent.com/8037152/111948030-75b26180-8b19-11eb-87ca-63ebe4b0656a.png)

**Comment by crossoverJie** [comment]
https://github.com/crossoverJie/gorm-optimistic/blob/6b4247192582c2907858b60d479e6d30af1095c7/optimistic_lock_test.go#L33

当不需要回调时， `callback` 允许为空。

**Comment by sjsdfg** [comment]
> https://github.com/crossoverJie/gorm-optimistic/blob/6b4247192582c2907858b60d479e6d30af1095c7/optimistic_lock_test.go#L33
> 
> 当不需要回调时， `callback` 允许为空。

你这个测试用例根本不能测到那个点。你这个就是跑一次的单侧。在本地环境下，你这个第一次执行就肯定成功了。根本不会进入到重试逻辑。

一旦进入到重试逻辑，你这里就的必须调用 callback。 你这里再传入一个nil。不就直接 panic 了。

**Comment by sjsdfg** [comment]
```
要么就下面的逻辑改了
if callback != nil {
    model = callback(model)
}
```

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/111950279-02125380-8b1d-11eb-9b17-c7f84857d0f6.png)

**Comment by sjsdfg** [comment]
如果 callback 允许为空和要 retryCount = 0 必须成对存在的话，前面的 readme 是没有体现的。而且这样也很容易引起误用。非常不可靠。

我这边是直接不连接到 mysql 来模拟更新失败的情况，只要 RetryCount 变大，就是必定 panic 的

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/111950777-b4e2b180-8b1d-11eb-8c8f-8cbb3cf6280e.png)
